var forMails;

function initPage(){
	sp = new Spinner(document.body,{message:WAIT_A_SECOND});
	
	
	
	$('addPoolMail').addEvent('click', function(evt) {
		forMails = true;
		POOLMODAL_SHOWAUTOGENERATED = false;
		POOLMODAL_SHOWCURRENTENV = true;
		ADDITIONAL_INFO_IN_TABLE_DATA = false;
		POOLMODAL_SHOWGLOBAL = true;
		POOLMODAL_EXACTMATCH = ""; 
		POOLMODAL_SELECTONLYONE	= false;
		showPoolsModal(processModalPoolsConfirm,null);
	});
	$('addPoolMsg').addEvent('click', function(evt) {
		forMails = false;
		POOLMODAL_SHOWAUTOGENERATED = false;
		POOLMODAL_SHOWCURRENTENV = true;
		ADDITIONAL_INFO_IN_TABLE_DATA = false;
		POOLMODAL_SHOWGLOBAL = true;
		POOLMODAL_EXACTMATCH = ""; 
		POOLMODAL_SELECTONLYONE	= false;
		showPoolsModal(processModalPoolsConfirm,null);
	});
	
	['schHrStart','schHrEnd', 'schBtwHrStart', 'schBtwHrEnd'].each(setHourField);
	
	
	initAdminFieldOnChangeHighlight();
	initAdminActionsEdition(beforeConfirm);
	initAdminFav();
	initPoolMdlPage();
	
	//cargar datepicker
	$$("input.datePickerCustom").each(function(datepicker) {
		datepicker.set('data-hasDatepicker', true);
		var img = new Element("img", {src: CONTEXT+"/css/base/img/calendar.png"});
		img.set('alt','datepicker');
		img.inject(datepicker,"after");

		var format = (datepicker.getAttribute("format") == null) ? DATE_FORMAT : datepicker.getAttribute("format");
		
		var datepicker_opts = { 
				pickerClass: 'datepicker_vista', 
				allowEmpty: true, 
				format: format, 
				inputOutputFormat: format, 
				toggleElements: img,
				toggleElementsDontAvoid: true,
				onClose: function(o){ validateDates(o); }
			};
		
		if(window.LBL_DAYS) {
			datepicker_opts.days = window.LBL_DAYS;
		}
		if(window.LBL_MONTHS) {
			datepicker_opts.months = window.LBL_MONTHS;
		}
		
		new DatePicker(datepicker, datepicker_opts);
	});
	
	startPage();
	
	getBodyController().canRemoveTab = function() { return ! AT_LEAST_ON_FIELD_INPUT_CHANGED; };
}

function beforeConfirm(){
	if (!checkNotifPools()){
		return false;
	}
	
	forMails = true;
	$('strPoolsMail').value = getStrPools();
	forMails = false;
	$('strPoolsMsg').value = getStrPools();
	$('strParameters').value = getStrParameters();
	
	return true;
}

function validateDates(obj){
	var dteStart = $('schDteStart');
	var hrMinStart = $('schHrStart');
	var dteEnd = $('schDteEnd');
	var hrMinEnd = $('schHrEnd');
	
	if(dteStart.value=='' || dteEnd.value=='') return;
	
	var datesOk = verifyDates(dteStart,dteEnd);
	var checkTime = true;
	if (equalsDates(dteStart, dteEnd)) 
		checkTime = verifyHrMin(hrMinStart,hrMinEnd,TIME_SEPARATOR);
	if (!datesOk || (datesOk && !checkTime)){
		showMessage(MSG_ERROR_DATE, GNR_TIT_WARNING, 'modalWarning');
		var toClear;
		if (obj == dteStart){
			toClear = dteStart;
		} else if (obj == hrMinStart){
			toClear = hrMinStart;
		} else if (obj == dteEnd){
			toClear = dteEnd;
		} else {
			toClear = hrMinEnd;
		}
		toClear.value = "";
		if (toClear == dteStart || toClear == dteEnd){
			toClear.getNext().value = "";		
		}
	}
}

function verifyTime(time){
	var hrMinStart = $('schHrStart');
	var hrMinEnd = $('schHrEnd');
	var dteStart = $('schDteStart');
	var dteEnd = $('schDteEnd');
	var timeEnter = time.value;
	
	if (hrMinStart.value == "" || hrMinEnd.value == "") return true;
	
	var datesOk = verifyDates(dteStart,dteEnd);
	var start = hrMinStart.value;
	var end = hrMinEnd.value;
	
	var arrS = new Array();
	var arrE = new Array();

	arrS = start.split(TIME_SEPARATOR);
	arrE = end.split(TIME_SEPARATOR);
	var endHr = arrE[0];
	var endMin = arrE[1];
	var startHr = arrS[0];
	var startMin = arrS[1];
	
	if (datesOk && dteStart.value == dteEnd.value && (endHr < startHr || endHr == startHr && endMin < startMin)){
		showMessage(MSG_ERROR_DATE, GNR_TIT_WARNING, 'modalWarning');
		if (timeEnter == start) {
			hrMinStart.value = "";
		} else {
			hrMinEnd.value = "";
		}
	}
	return true;
}

function startPage(){
	if ($('schNodeName').value != null && $('schNodeName').value != ""){
		var value = $('schNodeName').value;
		$('schNode').selectedIndex = 1;
		$('schNode').value = "1";
		changeNode($('schNode'));
		$('schNodeName').value = value;
	}
	
	if ($('schPeriodicity').value == "after_scheduler"){
		$('divSchPerAfterSch').setStyle("display","");
		if (!$('schPerAfterSch').hasClass("validate['required']")){
			$('schPerAfterSch').addClass("validate['required']");
			$('frmData').formChecker.register($('schPerAfterSch'));
		}
		$('schNodeName').setAttribute("disabled",true);
		$('schNode').setAttribute("disabled",true);
		hideAndIgnoreDates();
		
	} else if ($('schPeriodicity').value == "manually") {
		var startDate = $('schDteStart');
		var startTime = $('schHrStart');
		var endTime = $('schDteEnd');
		
		if (startDate){
			var children = startDate.getParent().getChildren();
			for (i = 0; i < children.length; i++) {
				if (children[i].tagName.toLowerCase() == 'input') {
					children[i].removeClass("validate['required']");
					$('frmData').formChecker.dispose(children[i]);
				}
			}
			startTime.removeClass("validate['required','%hourMinute']");
			$('frmData').formChecker.dispose(startTime);
			var startDoubleParent = startDate.getParent().getParent();
			var endDoubleParent = endTime.getParent().getParent();
			startDoubleParent.style.display = 'none';
			endDoubleParent.style.display = 'none';
		}
	}
	
	loadParameters();
	
	if ($('schErrDis').value == "true"){
		$('schErrDis').checked = true;
	}
	if ($('schErrSndMail').value == "true"){
		$('schErrSndMail').checked = true;		
	}
	if ($('schErrSndMsg').value == "true"){
		$('schErrSndMsg').checked = true;		
	}	
	
	chkValue($('schErrSndMail'), true);
	chkValue($('schErrSndMsg'), false);
	
	loadPools();	
	
	if ($('schNotMaxExe').value == "true"){
		$('schNotMaxExe').checked = true;
	}
	chkNotMaxExecution($('schNotMaxExe'));
}

function afterOtherSch(cmb){
	var cmbSchs = $('schPerAfterSch');
	var container = $('divSchPerAfterSch');
	
	//processNodeSch set disable = true
	$('schNodeName').removeAttribute("disabled");
	$('schNode').removeAttribute("disabled");
	
	cmbSchs.value = "";
	
	if (cmbSchs) {
		container.style.display = 'none'
		if (cmbSchs.hasClass("validate['required']")){
			cmbSchs.removeClass("validate['required']");
			$('frmData').formChecker.dispose(cmbSchs);
		}
	}
	
	if (cmb.value == "after_scheduler"){
		container.setStyle("display","");
		$('frmData').formChecker.dispose(cmbSchs);
		if (!cmbSchs.hasClass("validate['required']")){
			cmbSchs.addClass("validate['required']");
		}
		$('frmData').formChecker.register(cmbSchs);
		hideAndIgnoreDates();
	} else if (cmb.value == "manually") {
		var startDate = $('schDteStart');
		var startTime = $('schHrStart');
		var endTime = $('schDteEnd');
		
		if (startDate){
			var children = startDate.getParent().getChildren();
			for (i = 0; i < children.length; i++) {
				if (children[i].tagName.toLowerCase() == 'input') {
					children[i].removeClass("validate['required']");
					$('frmData').formChecker.dispose(children[i]);
				}
			}
			startTime.removeClass("validate['required','%hourMinute']");
			$('frmData').formChecker.dispose(startTime);
			var startDoubleParent = startDate.getParent().getParent();
			var endDoubleParent = endTime.getParent().getParent();
			startDoubleParent.style.display = 'none';
			endDoubleParent.style.display = 'none';
		} 
		
		if (cmbSchs) {
			container.style.display = 'none'
			if (cmbSchs.hasClass("validate['required']")){
				cmbSchs.removeClass("validate['required']");
				$('frmData').formChecker.dispose(cmbSchs);
			}
		}
	} else {
		//si era manually y ya no
		var startDate = $('schDteStart');
		var startDoubleParent = startDate.getParent().getParent();
		
		if(startDoubleParent.style.display=='none'){
		
			container.setStyle("display","none");
			if (cmbSchs.hasClass("validate['required']")){
				cmbSchs.removeClass("validate['required']");
				$('frmData').formChecker.dispose(cmbSchs);
			}
			var startDate = $('schDteStart');
			var startTime = $('schHrStart');
			var endTime = $('schDteEnd');
			if (startTime) {
				var children = startDate.getParent().getChildren();
				for (i = 0; i < children.length; i++) {
					if (children[i].tagName.toLowerCase() == 'input') {
						if (!children[i].hasClass("validate['required']"))
							children[i].addClass("validate['required']");
						$('frmData').formChecker.register(children[i]);
					}
				}
				if (!startTime.hasClass("validate['required','%hourMinute']"))
					startTime.addClass("validate['required','%hourMinute']");
				$('frmData').formChecker.register(startTime);
				var startDoubleParent = startDate.getParent().getParent();
				var endDoubleParent = endTime.getParent().getParent();
				startDoubleParent.style.display = '';
				endDoubleParent.style.display = '';
			}
		}
	}
}

function changeNode(cmb){
	var input = $('schNodeName');
	var container = $('divSchNodeName');
	input.value = "";
	if (cmb.value == "1"){
		container.setStyle("display","");
		if (!input.hasClass("validate['required']")){
			input.addClass("validate['required']");
			$('frmData').formChecker.register(input);
		}
	} else {
		container.setStyle("display","none");
		if (input.hasClass("validate['required']")){
			input.removeClass("validate['required']");
			$('frmData').formChecker.dispose(input);
		}
	}
}

function chkValue(chk,isNotifMail){
	if (chk.checked){
		chk.value = "true";
	} else {
		chk.value = "false";
	}
	
	if (chk.getAttribute("id") == "schErrDis") return;
	
	var btnAdd = isNotifMail ? $('addPoolMail') : $('addPoolMsg');
	var container = isNotifMail ? $('mailPoolContainter') : $('msgPoolContainter');
	
	if (chk.checked){
		btnAdd.setStyle("display","");
	} else {
		if (container.getElements("div.pool").length > 0){
			var labelFor = isNotifMail ? NOTIF_MAIL : NOTIF_MSG;
			showConfirm(MSG_REM_POOLS.replace("<TOK1>",labelFor), GNR_TIT_WARNING, 
					function(ret){
						if (ret){ //confirma eliminar
							container.getElements("div.pool").each(function(pool){
								pool.destroy();
							});
							chk.checked = false;
							chk.value = "false";
							btnAdd.setStyle("display","none");
						} else {
							chk.checked = true;
							chk.value = "true";
							btnAdd.setStyle("display","");
						}
					}
				, 'modalWarning');
		} else {
			btnAdd.setStyle("display","none");
		}
	}
}

function loadParameters(cmb){
	var busClassId = "";
	if (cmb){
		busClassId = cmb.value;
	} else if (!MODE_CREATE){
		busClassId = $('schBusClass').value;
	}
	if (busClassId != ""){
		var request = new Request({
			method: 'post',
			url: CONTEXT + URL_REQUEST_AJAX + '?action=loadParameters&isAjax=true&id=' + busClassId + TAB_ID_REQUEST,
			onRequest: function() { SYS_PANELS.showLoading(); },
			onComplete: function(resText, resXml) { processParametersXml(resXml); SYS_PANELS.closeAll(); }
		}).send();
	} else {
		cleanParameters();
		$('divParams').setStyle("visibility","hidden");
	}
}

function unescapeHTML(html) {
	var textarea = new Element('textarea');
	textarea.innerHTML = html;
	var unescape = textarea.textContent;
	textarea.destroy();
	return unescape;
}

function processParametersXml(ajaxCallXml){
	cleanParameters();
	var hasParams = false;
	var container = $('parametersContainter');
	$('divParams').setStyle("visibility","");
	if (ajaxCallXml != null) {
		var parameters = ajaxCallXml.getElementsByTagName("parameters");
		if (parameters != null && parameters.length > 0 && parameters.item(0) != null) {
			parameters = parameters.item(0).getElementsByTagName("parameter");
			
			var xmlParam;			
			for(var i = 0; i < parameters.length; i++) {
				hasParams = true;
				xmlParam = parameters[i];
				
				var p = new Element("div",{'class': 'option optionWidthParameter left', 'id': "param_"+xmlParam.getAttribute("id") }).inject(container);				
				var eleName = new Element('div', {'class': 'optionParameterName', html: xmlParam.getAttribute("name")+": "}).inject(p);
				
				p.setAttribute("idNum",xmlParam.getAttribute("id"));
				p.setAttribute("paramType",xmlParam.getAttribute("type"));
				
				var paddingLeft = eleName.getWidth() + 10 /* margin */;
				var divContainer = new Element('div',{'style':"width:initial;padding-left:"+ paddingLeft +"px;"}).inject(p);
				var input = new Element("input",{'type': 'text', 'id': "val_"+xmlParam.getAttribute("id"), 'value': unescapeHTML(xmlParam.getAttribute("value")), 'class':'optionParameter'}).inject(divContainer);
								
				if (xmlParam.getAttribute("type") == "D"){ //Date
					input.addClass("optionParameterDate datePickerCustom filterInputDate");
					input.setAttribute("format",DATE_FORMAT);
					input.setAttribute("maxlength","10");
					
					input.set('data-hasDatepicker', true);
					var img = new Element("img", {src: CONTEXT+"/css/base/img/calendar.png"});
					img.inject(input,"after");
					var format = (input.getAttribute("format") == null) ? DATE_FORMAT : input.getAttribute("format");
					
					var datepicker_opts = { 
							pickerClass: 'datepicker_vista', 
							allowEmpty: true, 
							format: format, 
							inputOutputFormat: format, 
							toggleElements: img,
							toggleElementsDontAvoid: true,
							onClose: function(o){ validateDates(o); }
						};
					
					if(window.LBL_DAYS) {
						datepicker_opts.days = window.LBL_DAYS;
					}
					if(window.LBL_MONTHS) {
						datepicker_opts.months = window.LBL_MONTHS;
					}
					new DatePicker(input, datepicker_opts);
				} else if (xmlParam.getAttribute("type") == "S"){ //String
					input.addClass("optionParameterString");
					input.setAttribute("maxlength","255");					
				} else { //Numeric
					input.addClass("optionParameterNumeric");
					input.setAttribute("maxlength","10");
					input.addClass("validate['number']");
					$('frmData').formChecker.register(input);
				}					
			}
			
			initAdminFieldOnChangeHighlight(false, false, false, $('parametersContainter'));
		}
	}
	
	if (!hasParams){
		var span = new Element("span", {'id': 'noParams', html: NO_PARAM }).inject(container);
		span.set('title', NO_PARAM_TT);		
	}
}

function cleanParameters(){
	$(parametersContainter).getElements("div").each(function(item){
		item.destroy();
	});	
	if ($('noParams')){ $('noParams').destroy(); }
}

function loadPools(){
	var request = new Request({
		method: 'post',
		url: CONTEXT + URL_REQUEST_AJAX + '?action=loadPools&isAjax=true' + TAB_ID_REQUEST,
		onRequest: function() { SYS_PANELS.showLoading(); },
		onComplete: function(resText, resXml) { processPoolsXml(resXml); SYS_PANELS.closeAll(); }
	}).send();
}

function processPoolsXml(ajaxCallXml){
	if (ajaxCallXml != null) {
		var notifications = ajaxCallXml.getElementsByTagName("notifications");
		if (notifications != null && notifications.length > 0 && notifications.item(0) != null) {
			var xmlPool;
			
			var notificationsMail = notifications.item(0).getElementsByTagName("mail");
			if (notificationsMail != null && notificationsMail.length > 0 && notificationsMail.item(0) != null) {
				notificationsMail = notificationsMail.item(0).getElementsByTagName("pool");
				forMails = true;			
				for(var i = 0; i < notificationsMail.length; i++) {
					xmlPool = notificationsMail[i];
					createPool(xmlPool.getAttribute("id"),xmlPool.getAttribute("name"),xmlPool.getAttribute("description"));				
				}
			}
			
			var notificationsMsg = notifications.item(0).getElementsByTagName("message");
			if (notificationsMsg != null && notificationsMsg.length > 0 && notificationsMsg.item(0) != null) {
				notificationsMsg = notificationsMsg.item(0).getElementsByTagName("pool");
				forMails = false;			
				for(var i = 0; i < notificationsMsg.length; i++) {
					xmlPool = notificationsMsg[i];
					createPool(xmlPool.getAttribute("id"),xmlPool.getAttribute("name"),xmlPool.getAttribute("description"));				
				}
			}
		}
	}
}

function createPool(poolId,poolName,poolDesc){
	var addBefore = $('addPoolMail');
	var pre = "mail_";
	if (!forMails) { pre = "msg_"; addBefore = $('addPoolMsg'); }
	
	var pool = new Element("div", {'id': pre+poolId, 'poolIdNum': poolId, html: poolName, 'class': 'option pool'});
	
	pool.setAttribute("poolName",poolName);
	if (poolDesc != null && poolDesc != "") { 
		pool.set('title', poolDesc);
		pool.setAttribute("poolDescription",poolDesc);
	} else {
		pool.setAttribute("poolDescription","");
	}
	
	new Element('div.optionRemove').addEvent('click', function(evt) { 
		if (pool.OBJtooltip){
			pool.OBJtooltip.hide()
		};
		pool.destroy(); 
	}).inject(pool);
	
	pool.inject(addBefore,"before")
}

function processModalPoolsConfirm(ret){
	var pre = "mail_";
	if (!forMails) { pre = "msg_"; }
	ret.each(function(e){
		var content;
		if (!$(pre+e.getRowId())){
			content = e.getRowContent();
			createPool(e.getRowId(),content[0],content[1]);
		}
	});	
}

function getStrPools(){
	var container = $('mailPoolContainter');
	var chk = $('schErrSndMail');
	if (!forMails) { 
		container = $('msgPoolContainter');
		chk = $('schErrSndMsg'); 
	}
	
	var strPools = "";
	
	if (chk.checked){
		container.getElements("div").each(function(item){
			var idNum = item.getAttribute("poolIdNum"); 
			if (idNum != null && idNum != ""){
				if (strPools != "") { strPools += ";"; }
				strPools += idNum + PRIMARY_SEPARATOR;
				strPools += item.getAttribute("poolName") + PRIMARY_SEPARATOR;
				strPools += item.getAttribute("poolDescription");
			}
		});
	}
	
	return strPools;
}

function getStrParameters(){
	var strParameters = "";
	var input;
	$('parametersContainter').getElements("div").each(function(item){
		input = $("val_"+item.getAttribute("idNum"));
		if (input){
			if (strParameters != "") { strParameters += PRIMARY_SEPARATOR; }
			strParameters += item.getAttribute("idNum") + PRIMARY_SEPARATOR;
			strParameters += input.value + PRIMARY_SEPARATOR;
			strParameters += item.getAttribute("paramType");
		}		
	});
	
	return strParameters;
}

function hourMinute(el){
	if (el.value == null || el.value == "") return true;
	
	var valueSplit = el.value.split(HOUR_SEPARATOR);
	if (valueSplit != null && valueSplit.length == 2){
		var hour = valueSplit[0]; 
		var min = valueSplit[1];
		if (!hour.test(/([0-1][0-9]|[2][0-3])/) || !min.test(/[0-5][0-9]/)){
			el.errors.push(VALID_HR);
	        return false;
		}
	} else {
		el.errors.push(VALID_HR);
        return false;
	}
	
	return true;
}

function checkNotifPools(){
	if ($('schErrSndMail').checked){
		if ($('mailPoolContainter').getElements("div.pool").length == 0){
			showMessage(MSG_MUST_BE_ADD_POOLS.replace("<TOK1>",NOTIF_MAIL), GNR_TIT_WARNING, 'modalWarning');
			return false;
		}
	}
	
	if ($('schErrSndMsg').checked){
		if ($('msgPoolContainter').getElements("div.pool").length == 0){
			showMessage(MSG_MUST_BE_ADD_POOLS.replace("<TOK1>",NOTIF_MSG), GNR_TIT_WARNING, 'modalWarning');
			return false;
		}
	}
	
	return true;
}

function chkNotMaxExecution(chk){
	if (chk.checked){
		chk.value = "true";
	} else {
		chk.value = "false";
	}
	
	[$('schMaxExeMails'),$('schMaxExeTime')].each(function(ele){
		if (chk.checked){
			ele.removeAttribute('disabled');
			ele.removeClass('readonly');
		} else {
			ele.setAttribute('disabled','');
			ele.addClass('readonly');
			ele.value='';
		}	
	})
}

function validateEmails(el){ //Validaci�n de los emails ingresados
	//Si se ingreso mas de un email, debe utilizarse el separador ';'
	var emails = $('schMaxExeMails').value;
	if (emails != ""){
		var RegEx =  $('frmData').formChecker.options.regexp.email;
		emails = emails.split(';');
		for(var i=0; i<emails.length; i++){
			if(!emails[i].match(RegEx)){
				el.errors.push(MSG_EMAILS_FORMAT_ERROR);
				return false;
			}   
		}
	}

    return true;
}

function actionChangeAfterSch(cmb){
	var schId = cmb.value;
	var request = new Request({
		method: 'post',
		url: CONTEXT + URL_REQUEST_AJAX + '?action=getSchNode&isAjax=true&id=' + schId + TAB_ID_REQUEST,
		onRequest: function() { SYS_PANELS.showLoading(); },
		onComplete: function(resText, resXml) { modalProcessXml(resXml); SYS_PANELS.closeAll(); }
	}).send();
	
}


function processNodeSch(){
	var xml = getLastFunctionAjaxCall();
	var inheritNode = xml.getElementsByTagName("message")[0].innerHTML;
	var input = $('schNodeName');
	var container = $('divSchNodeName');
	
	$("schNode").setAttribute('disabled', true);
	/* 0 = cualquier nodo*/
	if ($("schNode").value == 0){
		if (inheritNode != ""){
			$("schNode").value = 1;
			input.value = inheritNode;
			container.setStyle("display","");
		}
		
	}else /* 1 = Nodo especifico*/
		if ($("schNode").value = 1){
			if (inheritNode == ""){
				container.setStyle("display", "none");
				$("schNode").value = 0;
			} else {
				input.value = inheritNode;
				
			}
		}
	input.setAttribute('disabled',true);
	
}

function hideAndIgnoreDates(){
	var startDate = $('schDteStart');
	var startTime = $('schHrStart');
	var endTime = $('schDteEnd');
	
	if (startDate){
		var children = startDate.getParent().getChildren();
		for (i = 0; i < children.length; i++) {
			if (children[i].tagName.toLowerCase() == 'input') {
				children[i].removeClass("validate['required']");
				$('frmData').formChecker.dispose(children[i]);
			}
		}
		startTime.removeClass("validate['required','%hourMinute']");
		$('frmData').formChecker.dispose(startTime);
		var startDoubleParent = startDate.getParent().getParent();
		var endDoubleParent = endTime.getParent().getParent();
		startDoubleParent.style.display = 'none';
		endDoubleParent.style.display = 'none';
	}
}