<%@include file="../../../../includes/startInc.jsp" %><html><head><%@include file="../../../../includes/headInclude.jsp" %><script type="text/javascript" src="<system:util show="context" />/page/design/forms/formsDesigner/modals/treeModal.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/foldersDisplay.js"></script><link href="<system:util show="context" />/page/design/forms/formsDesigner/designer.css" rel="stylesheet" type="text/css" ></head><script type="text/javascript"><% if (request.getParameter("requestAction")!=null) { %>
	var URL_REQUEST_AJAX = '<%=request.getParameter("requestAction")%>';
	<% } else { %>
	var URL_REQUEST_AJAX = '/apia.design.FormsAction.run';
	<% } %>
	var ADDITIONAL_INFO_IN_TABLE_DATA = false;
	var LBL_STR_TYPE = '<system:label show="text" label="lblStr" forScript="true" />';
	var LBL_NUM_TYPE = '<system:label show="text" label="lblNum" forScript="true" />';
	var LBL_DATE_TYPE = '<system:label show="text" label="lblDate" forScript="true" />';
	var ATT_TAB_TITLE = '<system:label show="text" label="mnuDicDat" forScript="true" />';
</script><body><div class="body" id="bodyDiv" style="padding: 0 10px 0 10px; overflow: hidden; "><div style="width:100%;height:100%;float:left"><div class="fieldGroup" style="height: inherit;position: relative;"><div class="title" style="padding-top:5px;"><system:label show="text" label="lblFolders" /></div><div class="gridContainer mdlTableContainer" id="gridContainerFormAtts"><div style="height: 100%;width:100%;margin-left:0px;position: relative;" ><div id="paramGridHeader" class="gridHeader" style="position: absolute;width: 100%;"><table><thead><!-- 									<tr class="filter"> --><%-- 										<th title="<system:label show="tooltip" label="lblNom" />" width="100%"><div style=""><input id="nameFilter" type="text"></div></th> --%><!-- 									</tr> --></thead></table></div><div class="gridContainerWithFilter" style="padding-top: 0;"><div class="gridBody gridContainerFolder" style="height:100%; border-bottom: 1px solid #DDDDDD; overflow:auto;"><table style="table-layout: fixed;"><thead><tr class="header"><th class="hidden-th" width="100%"></th></tr></thead><tbody class="tableData" id="tableData"><tr><td><div><ul id="dcsFldsTreeMdl" class="fncContainer modal"></ul></div></td></tr></tbody></table></div></div></div></div></div></div></div></body>
