function initPage() {
	sp = new Spinner(document.body,{message:WAIT_A_SECOND});
	
	var btnAdd = $('addSysObject');
	if (btnAdd) {
		btnAdd.addEvent("click", function(e) {
			e.stop();
			var option = $('selNatLangType').value;
			if (option == 'F') {
				// form
				FORMSMODAL_SELECTONLYONE = true;
				showFormModal(processObjectModalReturn);
			} else if (option == 'P') {
				// process
				PROCESSMODAL_SELECTONLYONE = true;
				showProcessModal(processObjectModalReturn);
			} else if (option == 'B') {
				// business entities
				ENTITIESMODAL_SELECTONLYONE = true;
				showEntitiesModal(processObjectModalReturn);
			} else if (option == 'T') {
				// task
				TASKMODAL_SELECTONLYONE = true;
				showTaskModal(processObjectModalReturn);
			} else if (option == 'G') {
				// pool 
				POOLMODAL_SELECTONLYONE = true;
				POOLMODAL_SHOWGLOBAL = true;
				POOLMODAL_SHOWAUTOGENERATED = false;
				POOLMODAL_SHOWNOTAUTOGENERATED = true;
				showPoolsModal(processObjectModalReturn);
			}
		});
	}
	
	initAdminActionsEdition();
	
	var btnConf = $('btnConf');
	
	if (btnConf){
		btnConf.removeEvents();
		btnConf.addEvent("click", function(e) {
			if (e) e.stop();
			
			var form = $('frmData');
			if(!form.formChecker.isFormValid()){
				return;
			}
			
			var params = getFormParametersToSend(form);
			params += "&ctrlKeyPressedOnConfirm=" + e.control;
			
			if ($('addSysObject')) {
				if ($('addSysObject').isVisible()) {
					showMessage(SEL_ONE_ELEMENT, GNR_TIT_WARNING, 'modalWarning');
					return;
				}
			}
			
			var tableOptions = $('tableDataObj');
			if (tableOptions && tableOptions.children.length == 0) {
				showMessage(ADD_AT_LEAST_ONE_QUESTION, GNR_TIT_WARNING, 'modalWarning');
				return;
			}
			
			var request = new Request({
				method: 'post',
				url: CONTEXT + URL_REQUEST_AJAX + '?action=confirm&isAjax=true' + TAB_ID_REQUEST,
				onRequest: function() { SYS_PANELS.showLoading(); },
				onComplete: function(resText, resXml) { modalProcessXml(resXml); }
			}).send(params);
		
		});
	}
	
	var flag = $('flagAllElems');
	if (flag) {
		var selected = $('flagAllElems').checked;
		if (selected) {
			$('addSysObject').style.display = 'none';
		} else {
			$('addSysObject').style.display = '';
		}
	}
	
	if ($('selNatLangType')) {
		$('selNatLangType').addEvent('mouseover', function(evt) {
			if (evt) evt.stop();
			$('selNatLangType').previousIndex = $('selNatLangType').selectedIndex;
		});
	}
	
	initAdminFieldOnChangeHighlight();
//	initAdminFieldOnChangeHighlight($$('div.modalOptionsContainer')[0]);
	
	initDataTable();
	initObjectTable();
	initEntMdlPage();
	initFormMdlPage();
	initPoolMdlPage();
	initProcMdlPage();
	initTaskMdlPage();
}

function changeActions(cond) {
	var table = $('tableDataObj');
	var optionsAdded = document.getElementsByClassName('optionRemove');
	
	if ((table.getChildren('tr') && table.getChildren('tr').length > 0) || optionsAdded && optionsAdded.length > 0) {
		showConfirm("Se eliminaran todos los elementos agregados", GNR_TIT_WARNING, function(ret) {
			if (ret) {
				$('tableDataObj').innerHTML = '';
				
				var optionsAdded = document.getElementsByClassName('optionRemove');
				if (optionsAdded && optionsAdded.length > 0) {
					for (i = 0; i < optionsAdded.length; i++) {
						optionsAdded[i].fireEvent('click');
					}
				}
				
				if ($('selNatLangType').value == 'N' || $('selNatLangType').value == 'C') {
					$('middleOpts').style.display = 'none';
				} else {
					$('middleOpts').style.display = '';
				}
			} else {
				$('selNatLangType').selectedIndex = $('selNatLangType').previousIndex;
			}
		});
	}
}

function toggleAddBtn(chk) {
	if (chk.checked) {
		var optionsAdded = document.getElementsByClassName('optionRemove');
		if (optionsAdded && optionsAdded.length > 0) {
			for (i = 0; i < optionsAdded.length; i++) {
				optionsAdded[i].fireEvent('click');
			}
		}
		$('addSysObject').style.display = 'none';
	} else {
		$('addSysObject').style.display = '';
	}
}

function processObjectModalReturn(ret){
	ret.each(function(e){
		var text = e.getRowContent()[0];
		var proVer = e.getAttribute('proverid');
		$('addSysObject').style.display = 'none';
		addActionElement($('objectContainer'),text,e.getRowId(),"true",true, proVer);
	});
	$('groupCheckAll').style.display = 'none';
}

function addActionElement(container, text, id, helper, addRemove, versionProcess) {
	var repeated = false;
	//primero verificar que no exista
	container.getElements("DIV").each(function(item,index){
		if(item.getAttribute("id")==id){
			repeated = true;
		}
	});
	
	if(repeated) return;
	
	if (!versionProcess) {
		versionProcess = -1;
	}
	
	var divElement = new Element('div.option', {
		html: text,
		id: id,
		'data-helper': helper,
		'procVer': versionProcess
	});
	
	new Element('input', { type: 'hidden', name: 'objIdent', value: id}).inject(divElement);
	new Element('input', { type: 'hidden', name: 'objName', value: text}).inject(divElement);
	new Element('input', { type: 'hidden', name: 'objVersion', value: versionProcess}).inject(divElement);
	
	if(addRemove){
		divElement.container = container;
		new Element('div.optionRemove').addEvent('click', function(evt){
			actionElementAdminClickRemove.attempt(evt,this);
			$('addSysObject').style.display = '';
			$('groupCheckAll').style.display = '';
		}).inject(divElement);
	}
	divElement.inject(container.getLast(), 'before');
	return divElement;
}

function initDataTable() {
	var request = new Request({
		method: 'post',
		url: CONTEXT + URL_REQUEST_AJAX + '?action=getTableObjects' +  TAB_ID_REQUEST,
		onRequest: function() { SYS_PANELS.showLoading(); },
		onComplete: function(resText, resXml) { 
			populateTable(resXml);
			SYS_PANELS.closeAll();
		}
	}).send();
}

function populateTable(xml) {
	/*
	 * En el xml devuelto, si es distinto de custom deberian venir todas las opciones del combo, para ya cargar los mismos
	 * y setear el valor seleccionado
	 * */
	var table = $('tableDataObj');
//	initTable(table);
	if (xml) {
		var natLangType = xml.getElementsByTagName('object')[0].getAttribute('type');
//		var natLangType = xml.getElementsByTagName('main')[0].getAttribute('type');
		if (natLangType != 'N' && natLangType != 'C') {
			// creo el select para todas las filas
			var sysQuestions = xml.getElementsByTagName('sysQuest');
			var select;
			if (sysQuestions && sysQuestions.length > 0) {
				select = new Element('select');
				for (i = 0; i < sysQuestions.length; i++) {
					var optionData = sysQuestions[i];
					var option = new Element('option');
					option.innerHTML = optionData.getAttribute('objElem');
					option.setAttribute('value', optionData.getAttribute('objId'));
					select.add(option);
				}
				
			}
			
			var usrDefQuest = xml.getElementsByTagName('usrDefQuest');
			if (usrDefQuest && usrDefQuest.length > 0) {
				for (i = 0; i < usrDefQuest.length; i++) {
					var mySelect = select.cloneNode(true);
					mySelect.value = usrDefQuest[i].getAttribute('questRelated');
					var input = new Element('input');
					input.value = usrDefQuest[i].getAttribute('usrDefQuest');
					addRow(table, mySelect, input);
				}
				initTable(table);
			}
		} else {
			if (natLangType == 'N') {
				var commands = xml.getElementsByTagName('command');
				if (commands && commands.length > 0) {
					var selectFunc = new Element('select');
					for (i = 0; i < commands.length; i++) {
						var option = new Element('option');
						option.innerHTML = commands[i].getAttribute('objElem');
						option.setAttribute('value', commands[i].getAttribute('objId'));
						selectFunc.add(option);
					}
				}
			}
			
			var allElems = xml.getElementsByTagName('customOrFnc');
			if (allElems && allElems.length > 0) {
				for (i = 0; i < allElems.length; i++) {
					if (natLangType == 'N') {
						var mySelect = selectFunc.cloneNode(true);
						mySelect.value = allElems[i].getAttribute('relatedFunct');
						var input = new Element('input');
						input.value = allElems[i].getAttribute('functionOrQuest');
						addRow(table, mySelect, input);
					} else {
						var inputQ = new Element('input');
						inputQ.value = allElems[i].getAttribute('functionOrQuest');
						var inputA = new Element('input');
						inputA.value = allElems[i].getAttribute('answer');
						addRow(table, inputQ, inputA);
					}
				}
//				initTable(table);
			}
		}
		// add selected object
		var selected = xml.getElementsByTagName('object')[0];
		if (selected.getAttribute('id') && selected.getAttribute('name')) {
			addActionElement($('objectContainer'), selected.getAttribute('name'), selected.getAttribute('id'), "true", true);
			$('addSysObject').style.display = 'none';
			$('groupCheckAll').style.display = 'none';
		}
	}
}

function loadObjectChosen() {
	var request = new Request({
		method: 'post',
		url: CONTEXT + URL_REQUEST_AJAX + action +  TAB_ID_REQUEST,
		onRequest: function() { SYS_PANELS.showLoading(); },
		onComplete: function(resText, resXml) { 
			var questions = resXml.getElementsByTagName('object');
			if (questions.length > 0) {
				for (i = 0; i < questions.length; i++) {
					var child = questions[i];
					var option = new Element('option');
					option.innerHTML = child.getAttribute('objElem');
					option.setAttribute('value', child.getAttribute('objId'));
					element.add(option);
				}
			}
			SYS_PANELS.closeAll();
		}
	}).send();
}

function reloadQuestionsLanguage(cmb) {
	var questions = $$('select.txtQuest');
	if (questions && questions.length > 0) {
		Array.from(questions).each(function(elem) {
			var selected = elem.selectedIndex;
			elem.innerHTML = '';
			populateSelect(elem);
			elem.selectedIndex = selected;
		});
	}
}