<%@include file="../../includes/startInc.jsp" %><html lang="<%=biz.statum.apia.web.bean.BasicBeanStatic.getUserDataStatic(request).getLangCode()%>"><head><%@include file="../../includes/headInclude.jsp" %><script type="text/javascript" src="<system:util show="context" />/page/design/folders/folders.js"></script><script type="text/javascript" src="<system:util show="context" />/page/modals/foldersCreate.js"></script><script type="text/javascript" src="<system:util show="context" />/page/modals/pools.js"></script><script type="text/javascript" src="<system:util show="context" />/page/modals/users.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/navButtons.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/adminActions.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/adminFav.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/foldersDisplay.js"></script><script type="text/javascript">
		var URL_REQUEST_AJAX = '/apia.design.DocumentsFoldersAction.run';	
		var isAllEnvs = "true";
		var isGlobal = "true";
		var LBL_ALL_ENVS = '<system:label show="text" label="lblTodAmb" forScript="true" />';
		var ADDITIONAL_INFO_IN_TABLE_DATA  = true;
		var msgExpRegFail			= '<system:label show="text" label="msgExpRegFal" forScript="true" />';
		var msgExpRegOk			= '<system:label show="text" label="msgExpRegOk" forScript="true" />';		
		var MSG_USE_PROY_PERMS = '<system:label show="text" label="msgUseProyPerms" forScript="true" />';
		var MSG_PERM_WILL_BE_LOST = '<system:label show="text" label="msgPermDefWillBeLost" forScript="true" />';
		
		var MSG_ERR_LENGTH = '<system:label show="text" label="msgMaxPer" forScript="true" />';
		var MSG_ERR_SMALLER_SIZE = '<system:label show="text" label="msgBigThan" forScript="true" />';
		
		var CLOSED = '<system:edit show="value" from="theBean" field="closedFolderImg"/>';
		var OPENED = '<system:edit show="value" from="theBean" field="openedFolderImg"/>';
		
		var MSG_NO_ELEMENTS		= '<system:label show="text" label="lblNoRet" forScript="true" forHtml="true"/>';
		var MSG_NO_ENOUGH_PERMS	= '<system:label show="text" label="msgUsrNtHvPrms" forScript="true" forHtml="true"/>';
		
		var MSG_LAST_MOD_DATE = '<system:label show="text" label="lblFecUltMod" forScript="true" forHtml="true"/>';
		var LBL_FLDS_WILL_BE_DELETED = '<system:label show="text" label="lblDelSel" forScript="true" forHtml="true"/>';
	</script></head><body><div id="exec-blocker"></div><div class="body" id="bodyDiv"><form id="frmData"><div class="optionsContainer"><system:campaign inLogin="false" inSplash="false" location="verticalUp" /><div class="fncPanel info"><div class="title"><system:label show="text" label="mnuFold" /><%@include file="../../includes/adminFav.jsp" %></div><div class="content divFncDescription"><div id="fncDescriptionText"><system:label show="text" label="dscFncAdmFold"/></div><div class="clear"></div></div></div><%@include file="../../includes/adminActions.jsp" %><div class="fncPanel options" id="panelOptions"><div class="title"><system:label show="text" label="mnuOpc" /></div><div class="content"><div class="filter"><div id="collapseStruct" class="button extendedSize"><system:label show="text" label="lblCollAll" /></div></div><%-- 						<div class="filter"><div id="btnFocus" class="button extendedSize"><system:label show="text" label="lblFocus" /></div></div> --%></div><div class="clear"></div></div><div class="fncPanel options lastOptions"><div class="title" title="<system:label show="tooltip" label="titAdmAdtFilter"/>"><system:label show="text" label="titAdmAdtFilter"/></div><div class="content"><div class="filter"><span><system:label show="text" label="titOrderBy" />:</span><select name="filterOrder" id="filterOrder" onchange="sortViewStructure()"><option value="1"><system:label show="text" label="lblOrdrAlphAsc"/></option><option value="2"><system:label show="text" label="lblOrdrAlphDesc"/></option><option value="3"><system:label show="text" label="lblOrdrModDateAsc"/></option><option value="4"><system:label show="text" label="lblOrdrModDateDesc"/></option></select></div><div class="clear"></div><div class="filter"><span><system:label show="text" label="lblFilByName" />:</span><input type="text" id="filterName" value="<system:filter show="value" filter="1"></system:filter>"></div><div class="clear"></div><div class="filter"><span><system:label show="text" label="lblClssDate"/>:</span><input id="filterStDte" type="text" size="9" maxlength="10" class="datePicker datePickerChecker filterInputDate" value="<system:filter show="value" filter="1"></system:filter>">
							- 
							<input id="filterEndDte" type="text" size="9" maxlength="10" class="datePicker datePickerChecker filterInputDate" value="<system:filter show="value" filter="2"></system:filter>"></div><div class="clear"></div><div class="filter"><span><system:label show="text" label="lblShwLastModDte"/>:</span><input type="checkbox" onchange="showHideDate(this)" id="chkSwLastModMade"></div></div></div><system:campaign inLogin="false" inSplash="false" location="verticalDown" /></div><div class="dataContainer"><div class='tabComponent' id="tabComponent"><div class="aTabHeader"><system:campaign inLogin="false" inSplash="false" location="horizontalUp" /></div><div class="aTab"><div class="tab" id="generalTab"><system:label show="text" label="tabFld" /></div><div class="contentTab"><div class="gridBody" id="gridBody" style="overflow:auto;"><!-- Cuerpo de la tabla --><table><thead></thead><tbody class="tableData" id="tableData"><div id="folders" class="foldersStruct"><ul id="foldersStruct"></ul></div></tbody></table></div><div class="gridFooter"><jsp:include page="/page/includes/navButtons.jsp"/></div><system:campaign inLogin="false" inSplash="false" location="horizontalDown" /></div></div></div></div></form></div><%@include file="../../includes/footer.jsp" %><%@include file="../../modals/foldersCreate.jsp" %></body></html>

